name: NEXT_CI_Workflow

on:
  push:
    branches: [ nextjs ]
  pull_request:
    branches: [ nextjs ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check out code to Build
      uses: actions/checkout@v2
    
    
      
    - name: Install dependencies
      run: npm install

    - name: Run ESLint
      run: npm run lint

    - name: Format code with Prettier
      run: npm run format
      
    - name: Build Next.js app
      run: npm run build

    - name: Run tests
      run: npm test

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
 
    - name: Build Docker image
      run: docker build -t ankitmahnmims/myappgo .

    - name: Push Docker image to Docker Hub
      run: docker push ankitmahnmims/myappgo:latest
    # - name: push to dockerhub
    #   uses: mr-smithers-excellent/docker-build-push@v6
    
    
    # - name: login to docker registry
    #     uses: docker/login-action@v3
    #     with:
    #       username: ${{secrets.DOCKER_USERNAME}}
    #       password: ${{secrets.DOCKER_PASSWORD}}
    
   
        
