name: PHP_CI_Workflow

on:
  push:
    branches: [ phpcode ]
  pull_request:
    branches: [ phpcode ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check out code to Build
      uses: actions/checkout@v2
    
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
    
    # - name: phpcs dependency
    #   run: composer require squizlabs/php_codesniffer:^3.4
    - name: Update Composer configuration
      run: composer global config allow-plugins true  
      
    - name: Install dependencies
      run: |
        composer update
        composer install --no-progress --no-suggest
        composer global require squizlabs/php_codesniffer
        composer global require wp-coding-standards/wpcs

    - name: Run PHPCS
      run: ~/.composer/vendor/bin/phpcs --standard=WordPress src/
      
    - name: Run tests
      run: phpunit

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
 
    - name: Build Docker image
      run: docker build -t ankitmahnmims/myappgo .

    - name: Push Docker image to Docker Hub
      run: docker push ankitmahnmims/myappgo:latest
    # - name: push to dockerhub
    #   uses: mr-smithers-excellent/docker-build-push@v6
    #   with:
    #     image: ankitmahnmims/myappgo/myapp
    #     registry: docker.io
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}
    
    # - name: login to docker registry
    #     uses: docker/login-action@v3
    #     with:
    #       username: ${{secrets.DOCKER_USERNAME}}
    #       password: ${{secrets.DOCKER_PASSWORD}}
    
    # - name: build and push docker image to registry
    #     uses: docker/build-push-action@v5
    #     with:
    #       context: ./Dockerfile
    #       push: true
    #       tags: myappgo/ankitnm:latest

    # - name: Build & push Docker image
 
        
