name: Go_CI_Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check out code to Build
      uses: actions/checkout@v2
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.19'
      
    - name: Install Go and Run Code Linting
      id: Lint-Check
      uses: reviewdog/action-golangci-lint@v2
      
      
    - name: Build Code
      id: Build-Code
      run: |
        go build -v .
        
    - name: Unit Test
      id: Unit-Test-Run
      run: |
        go test
    
    - name: login to docker registry
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
    
    - name: build and push docker image to registry
        uses: docker/build-push-action@v5
        with:
          context: ./
          push: true
          tags: myappgo/ankitnm:latest

    # - name: Build & push Docker image
    #   id: Build-and-Push-Docker-Image
    #   uses: mr-smithers-excellent/docker-build-push@v5
    #   with:
    #     image: myappgo/image
    #     tags: latest
    #     registry: registry-url.io
    #     dockerfile: Dockerfile
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}
        