name: NEXT_CI_Workflow

on:
  push:
    branches: [ nextjs ]
  pull_request:
    branches: [ nextjs ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check out code to Build
      uses: actions/checkout@v2
    
    
      
    - name: Install dependencies
      run: npm install

    - name: Run ESLint
      run: npm run lint

    - name: Format code with Prettier
      run: npm run format
      
    - name: Build Next.js app
      run: npm run build

    - name: Run tests
      run: npm test

    # - name: Login to Docker Hub
    #   run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
 
    # - name: Build Docker image
    #   run: docker build -t ankitmahnmims/myappgo .

    # - name: Push Docker image to Docker Hub
    #   run: docker push ankitmahnmims/myappgo:latest

    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: ankitmahnmims/myappnext
      
    - name: Build and push Docker image
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
   
    
   
        
